syntax = "proto3";

package grpcsso;

option go_package = "github.com/dmi3midd/grpcsso-protos/gen/go/grpcssov1";

message HasPermissionsRequest {
  string user_id = 1;
  string client_id = 2;
  repeated string permissions = 3;
}

message HasPermissionsResponse {
  bool has_permissions = 1;
}

message GetPermissionsRequest {
  string user_id = 1;
  string client_id = 2;
}

message GetPermissionsResponse {
  repeated string permissions = 1;
}

message AddPermissionsRequest {
  string user_id = 1;
  string client_id = 2;
  repeated string permissions = 3;
}

message AddPermissionsResponse {
  repeated string permissions = 3;
}

message RemovePermissionsRequest {
  string user_id = 1;
  string client_id = 2;
  repeated string permissions = 3;
}

message RemovePermissionsResponse {}

service PermissionService {
  rpc HasPermissions(HasPermissionsRequest) returns (HasPermissionsResponse);
  rpc GetPermissions(GetPermissionsRequest) returns (GetPermissionsResponse);
  rpc AddPermissions(AddPermissionsRequest) returns (AddPermissionsResponse);
  rpc RemovePermissions(RemovePermissionsRequest) returns (RemovePermissionsResponse);
}
