syntax = "proto3";

package grpcsso;

option go_package = "github.com/dmi3midd/grpcsso-protos/gen/go/grpcssov1";

message GetPermissionRequest {
    string permission_id = 1;
}
message GetPermissionResponse {
    string permission_id = 1;
    string name = 2;
}

message CreatePermissionRequest {
    string name = 1;
}
message CreatePermissionResponse {
    string permission_id = 1;
}

message DeletePermissionRequest {
    string permission_id = 1;
}
message DeletePermissionResponse {
    string permission_id = 1;
}

message AssignPermissionRequest {
    string permission_id = 1;
    string role_id = 2;
}
message AssignPermissionResponse {
    string permission_id = 1;
    string role_id = 2;
}

message RevokePermissionRequest {
    string permission_id = 1;
    string role_id = 2;
}
message RevokePermissionResponse {
    string permission_id = 1;
    string role_id = 2;
}

message GetRolePermissionsRequest {
    string role_id = 1;
}
message Permission {
    string permission_id = 1;
    string name = 2;
}
message GetRolePermissionsResponse {
    string role_id = 1;
    repeated Permission permissions = 2;
}
