syntax = "proto3";

package grpcsso;

option go_package = "github.com/dmi3midd/grpcsso-protos/gen/go/grpcssov1";

message InitiateResetPasswordRequest {
  string email = 1;
}

message InitiateResetPasswordResponse {
  string email = 1;
  string token = 2;
}

message ConfirmResetPasswordRequest {
  string email = 1;
  string token = 2;
  string new_password = 3;
}

message ConfirmResetPasswordResponse {}

service ResetPasswordService {
  rpc InitiateResetPassword(InitiateResetPasswordRequest) returns (InitiateResetPasswordResponse);
  rpc ConfirmResetPassword(ConfirmResetPasswordRequest) returns (ConfirmResetPasswordResponse);
}
