syntax = "proto3";

package grpcsso;

option go_package = "github.com/dmi3midd/grpcsso-protos/gen/go/grpcssov1";

message RegistrationRequest {
  string username = 1;
  string email = 2;
  string password = 3;
  repeated string permissions = 4;
  string client_id = 5;
}

message RegistrationResponse {
  string user_id = 1;
}

message ConfirmRegistrationRequest {
  string user_id = 1;
  string token = 2;
}

message ConfirmRegistrationResponse {
  string user_id = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
  string client_id = 3;
}

message User {
  string user_id = 1;
  string username = 2;
  string email = 3;
  repeated string permissions = 4;
}

message LoginResponse {
  User user = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {}

message RefreshRequest {
  string client_id = 1;
  string refresh_token = 2;
}

message RefreshResponse {
  User user = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message ResetPasswordRequest {
  string email = 1;
}

message ResetPasswordResponse {
  string email = 1;
  string token = 2;
}

message ConfirmResetPasswordRequest {
  string email = 1;
  string token = 2;
  string new_password = 3;
}

message ConfirmResetPasswordResponse {}

service AuthService {
  rpc Registration(RegistrationRequest) returns (RegistrationResponse);
  rpc ConfirmRegistration(ConfirmRegistrationRequest) returns (ConfirmRegistrationResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc ConfirmResetPassword(ConfirmResetPasswordRequest) returns (ConfirmResetPasswordResponse);
}
